advanced_analytics: false
animation_enabled: true
anonymize_exports: false
api_base_url: http://localhost:5000/api
api_retry_attempts: 3
api_retry_delay: 1.0
api_timeout: 30
auto_phase_advance: false
auto_save_interval: 300
auto_sync: true
beta_tools: false
bidirectional_sync: true
bridge_enabled: true
cache_expiry_hours: 24
color_scheme: cosmic
database_url: null
debug_mode: false
default_oracle_context: general
default_sigil_style: cosmic
default_sonic_frequency: healing
encrypt_local_data: false
experimental_features: false
export_formats:
- json
- yaml
- txt
geometry_color_palettes:
  cosmic:
  - '#191970'
  - '#4B0082'
  - '#8A2BE2'
  - '#9932CC'
  golden:
  - '#FFD700'
  - '#FFA500'
  - '#FF8C00'
  - '#DAA520'
  mystical:
  - '#4B0082'
  - '#8A2BE2'
  - '#9932CC'
  - '#6A5ACD'
  nature:
  - '#228B22'
  - '#32CD32'
  - '#90EE90'
  - '#98FB98'
geometry_default_size: 800
geometry_render_quality: high
log_file_path: mystical_system.log
log_level: INFO
log_to_file: true
lunareth_enabled: true
max_session_history: 100
mystical_theme: true
phase_transition_duration: 24.0
python_scripts_path: mystical_python
require_auth: false
sacred_constants:
  phi: 1.618033988749
  pi_sacred: 6.283185307179586
  spiral_constant: 0.3090169943749474
sacred_geometry_enabled: true
session_persistence: true
shared_data_path: shared_mystical_data
shared_state_file: shared_mystical_state.json
sync_interval: 30.0
tool_session_timeout: 3600
use_local_storage: true
websocket_bridge_enabled: false
